# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: positions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='positions.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fpositions.proto\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x8d\x01\n\tLocations\x12,\n\tlocations\x18\x01 \x03(\x0b\x32\x19.Locations.LocationsEntry\x12\x18\n\x08waypoint\x18\x02 \x01(\x0b\x32\x06.Point\x1a\x38\n\x0eLocationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Point:\x02\x38\x01\"j\n\x11\x43onnectionRequest\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.ConnectionRequest.ConnectionType\"$\n\x0e\x43onnectionType\x12\x07\n\x03GLS\x10\x00\x12\t\n\x05ROBOT\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONNECTIONREQUEST_CONNECTIONTYPE = _descriptor.EnumDescriptor(
  name='ConnectionType',
  full_name='ConnectionRequest.ConnectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GLS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROBOT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=275,
  serialized_end=311,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONREQUEST_CONNECTIONTYPE)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='Point.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=59,
)


_LOCATIONS_LOCATIONSENTRY = _descriptor.Descriptor(
  name='LocationsEntry',
  full_name='Locations.LocationsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Locations.LocationsEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Locations.LocationsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=203,
)

_LOCATIONS = _descriptor.Descriptor(
  name='Locations',
  full_name='Locations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='Locations.locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoint', full_name='Locations.waypoint', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LOCATIONS_LOCATIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=203,
)


_CONNECTIONREQUEST = _descriptor.Descriptor(
  name='ConnectionRequest',
  full_name='ConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ConnectionRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONNECTIONREQUEST_CONNECTIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=311,
)

_LOCATIONS_LOCATIONSENTRY.fields_by_name['value'].message_type = _POINT
_LOCATIONS_LOCATIONSENTRY.containing_type = _LOCATIONS
_LOCATIONS.fields_by_name['locations'].message_type = _LOCATIONS_LOCATIONSENTRY
_LOCATIONS.fields_by_name['waypoint'].message_type = _POINT
_CONNECTIONREQUEST.fields_by_name['type'].enum_type = _CONNECTIONREQUEST_CONNECTIONTYPE
_CONNECTIONREQUEST_CONNECTIONTYPE.containing_type = _CONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Locations'] = _LOCATIONS
DESCRIPTOR.message_types_by_name['ConnectionRequest'] = _CONNECTIONREQUEST

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'positions_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)

Locations = _reflection.GeneratedProtocolMessageType('Locations', (_message.Message,), dict(

  LocationsEntry = _reflection.GeneratedProtocolMessageType('LocationsEntry', (_message.Message,), dict(
    DESCRIPTOR = _LOCATIONS_LOCATIONSENTRY,
    __module__ = 'positions_pb2'
    # @@protoc_insertion_point(class_scope:Locations.LocationsEntry)
    ))
  ,
  DESCRIPTOR = _LOCATIONS,
  __module__ = 'positions_pb2'
  # @@protoc_insertion_point(class_scope:Locations)
  ))
_sym_db.RegisterMessage(Locations)
_sym_db.RegisterMessage(Locations.LocationsEntry)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONREQUEST,
  __module__ = 'positions_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionRequest)
  ))
_sym_db.RegisterMessage(ConnectionRequest)


_LOCATIONS_LOCATIONSENTRY.has_options = True
_LOCATIONS_LOCATIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
