# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dwdistance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dwdistance.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x64wdistance.proto\"]\n\nDwDistance\x12\x0f\n\x07send_id\x18\x02 \x01(\r\x12\x0f\n\x07recv_id\x18\x03 \x01(\r\x12\x0c\n\x04\x64ist\x18\x04 \x01(\x01\x12\x0e\n\x06\x62\x65\x61\x63on\x18\x05 \x01(\x08J\x04\x08\x01\x10\x02R\ttimestampb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DWDISTANCE = _descriptor.Descriptor(
  name='DwDistance',
  full_name='DwDistance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_id', full_name='DwDistance.send_id', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recv_id', full_name='DwDistance.recv_id', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dist', full_name='DwDistance.dist', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beacon', full_name='DwDistance.beacon', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['DwDistance'] = _DWDISTANCE

DwDistance = _reflection.GeneratedProtocolMessageType('DwDistance', (_message.Message,), dict(
  DESCRIPTOR = _DWDISTANCE,
  __module__ = 'dwdistance_pb2'
  # @@protoc_insertion_point(class_scope:DwDistance)
  ))
_sym_db.RegisterMessage(DwDistance)


# @@protoc_insertion_point(module_scope)
